apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgis-deployment
  labels:
    app: postgis-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgis-app
    spec:
      containers:
      - image: redis:latest
        imagePullPolicy: Always
        name: postgis-container
        ports:
        - containerPort: 5432
          protocol: TCP
        env:
        - name: POSTGRES_DB
          value: majinuni
        - name: POSTGRES_USER
          value: majinuni_user
        - name: POSTGRES_PASSWORD
          value: majinuni
