apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: python-app-deployment
  labels:
    app: python-app
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 180
  selector:
    matchLabels:
      app: python-app
      version: "v$TRAVIS_BUILD_NUMBER"
      lang: python
  template:
    metadata:
      labels:
        app: python-app
        version: "v$TRAVIS_BUILD_NUMBER"
        lang: python
    spec:
      containers:
        - name: python-app
          image: registry.ng.bluemix.net/test_api_registry_namespace/ibm_water_hackathon_bear:v30  # v$TRAVIS_BUILD_NUMBER
          imagePullPolicy: Always
          resources:
            limits:
              # cpu: 0.1
              memory: 500Mi
            requests:
              memory: 500Mi
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgis://majinuni_user:majinuni@postgis-service:5432/majinuni
