apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgis
  name: postgis-service
spec:
  ports:
  - name: "5432"
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgis-app
