apiVersion: v1
kind: Service
metadata:
  name: python-service
  labels:
    app: python-app
    lang: python
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  selector:
    lang: python
    app: python-app
